project:
  type: book

book:
  title: "How we built a Pragmatic Machine Learning Pipeline to Identify Fake Flysheets as part of a Library Workflow"
  author:
    - Daniel van Strien
    - Catherine Cronin
    - Andrew Longworth
    - Francisco Perez-Garcia
    - Adelaida Ngowi
    - Kate Thomas
  date: "today"
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - intro.qmd
        - business_problem.qmd
    - part: data.qmd
      chapters:
        - creating-training-data-annotation.qmd
        - creating-training-data-continued.qmd
    # - part: "Training models"
    #   chapters:
    #     - 00_baseline_dummy.ipynb
    #     - 02_cnn_baseline.ipynb
    # - part: "Appendices"
    #   chapters:
    #     - 05_onnx_conversion.ipynb
    #     - references.qmd

bibliography: references.bib
twitter-card: true
format:
  html:
    theme: cosmo

  #pdf:
#     documentclass: scrreprt

execute:
  freeze: true

csl: chicago-note-bibliography.csl
