project:
  type: book

book:
  title: "How we built a Pragmatic Machine Learning Pipeline to Identify Fake Flysheets as part of a Library Workflow"
  author:
    - Daniel van Strien
    - Catherine Cronin
    - Andrew Longworth
    - Francisco Perez-Garcia
    - Adelaida Ngowi
    - Kate Thomas
  date: "today"
  chapters:
    - index.qmd
    - intro.qmd
    - business_problem.qmd
    - references.qmd
  twitter-card: true
bibliography: references.bib

format:
  html:
    theme: cosmo

  #pdf:
#     documentclass: scrreprt

execute:
  freeze: auto
